routes/web.php
<?php
use App\Article;
use App\User;
use App\Comment;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $article = Article::all();
    return view('welcome',compact('article'));
});

Route::resource('articles','ArticleController')->middleware('auth');

Route::resource('profiles','ProfileController');

Route::get('/profile', function () {
    return view('profile');
});

Route::resource('comments','CommentController');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// Route::get('/comments', function () {
//     $comment = Comment::all();
//     return view('/articles/show',compact('comment'));
// });

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    protected $table = "articles";

    protected $guarded = [];
}

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $table = "comments";

    protected $guarded = [];
}

app/Profile.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Profile extends Model
{
    protected $table = "profiles";
    protected $guarded = [];

    public function user(){
        return $this->belongsTo('App\User');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function profile(){
        return $this->hasOne('App\Profile');
    }
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\Article;

class ArticleController extends Controller
{
    public function create(){
        return view('articles.create');
    }

    public function store(request $request){
        //dd($request->all());
        $request->validate([
            'judul' => 'required',
            'isi_artikel' => 'required'
        ]);

        $post = Article::create([
            "judul" => $request["judul"],
            "isi_artikel" => $request["isi_artikel"] 
        ]);

        return redirect('/articles')->with('success','Artikel Berhasil Dibuat!');
    }

    public function index(){
         
        $article = Article::all();
        return view('articles.index', compact('article'));
    }

    public function show($id){
        $post = Article::find($id);
        return view('articles.show', compact('post'));
    }

    public function edit($id){
        $post = Article::find($id);
        return view('articles.edit', compact('post'));
    }

    public function update($id, request $request){

        $update = Article::where('id',$id)->update([
            "judul" => $request["judul"],
            "isi_artikel" => $request["isi_artikel"] 
        ]);
        
        return redirect('/articles')->with('success','Berhasil update artikel!');
    }

    public function destroy($id){
        Article::destroy($id);
        return redirect('/articles')->with('success','Artikel berhasil dihapus');
    }
}

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\Comment;
use App\User;

class CommentController extends Controller
{
    public function index(){
        $post = Comment::all();
        return view('comment', compact('post'));
    }

    public function store(request $request){
        //dd($request->all());
        $request->validate([
            'isi_komentar' => 'required',
            
        ]);

        $post = Comment::create([
            "isi_komentar" => $request["isi_komentar"]
            
        ]);

        return redirect('/articles')->with('success','Data Berhasil Dibuat!');
    }

    public function show($id){
        $post = Comment::find($id);
        return view('comment', compact('post'));
    }

    public function edit($id){
        $post = Comment::find($id);
        return view('comment', compact('post'));
    }

    public function update($id, request $request){

        $update = Comment::where('id',$id)->update([
            "isi_komentar" => $request["isi_komentar"]
            
        ]);
        
        return redirect('comment')->with('success','Berhasil update data!');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Article;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        //return view('home');
        $article = Article::all();
        return view('home',compact('article'));
    }
}

app/Http/Controllers/ProfileController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\Profile;

class ProfileController extends Controller
{

    public function index(){
        $post = Profile::all();
        return view('profile', compact('post'));
    }

    public function store(request $request){
        //dd($request->all());
        $request->validate([
            'nama_lengkap' => 'required',
            // 'photo' => '',
            'jumlah_artikel' => 'required',
            'jumlah_following' => 'required',
            'jumlah_follower' => 'required'
        ]);

        $post = Profile::create([
            "nama_lengkap" => $request["nama_lengkap"],
            // "photo" => $request["photo"],
            "jumlah_artikel" => $request["jumlah_artikel"],
            "jumlah_following" => $request["jumlah_following"],
            "jumlah_follower" => $request["jumlah_follower"],
        ]);

        return redirect('profile')->with('success','Data Berhasil Dibuat!');
    }

    public function show($id){
        $post = Profile::find($id);
        return view('profile', compact('post'));
    }

    public function edit($id){
        $post = Profile::find($id);
        return view('profile', compact('post'));
    }

    public function update($id, request $request){

        $update = Profile::where('id',$id)->update([
            "nama_lengkap" => $request["nama_lengkap"],
            // "photo" => $request["photo"],
            "jumlah_artikel" => $request["jumlah_artikel"],
            "jumlah_following" => $request["jumlah_following"],
            "jumlah_follower" => $request["jumlah_follower"], 
        ]);
        
        return redirect('profile')->with('success','Berhasil update data!');
    }

}

resources/views/articles/create.blade.php
@extends('..layouts.app')
@section('content')
<div class="container">
<div class="row justify-content-center">
<div class="col-md-8">
<h1 class="my-4">Buat Arikel Baru</h1>
<form role="form" action="/articles" method="post">
    @csrf
    @method('POST')
    <div class="card-body">
        <div class="form-group">
            <label for="judul">Judul Artikel</label>
            <input type="text" class="form-control" id="judul" name="judul" value="{{ old('judul','') }}" placeholder="Judul Artikel">
            @error('judul')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror

            <br><br>
            <label for="isi_artikel">Isi Artikel</label>
            <textarea class="form-control" id="isi_artikel" name="isi_artikel" value="{{ old('isi_artikel','') }}"  style="height:500px" placeholder="Isi Artikel"></textarea>
            @error('isi_artikel')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror

        </div>
        <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
</form>
</div>
</div>
</div>
@endsection

resources/views/articles/edit.blade.php
@extends('..layouts.app')
@section('content')
<div class="container">
<div class="row justify-content-center">
<div class="col-md-8">
<h1 class="my-4">Edit Artikel</h1>
<form role="form" action="/articles/{{$post->id}}" method="post">
    @csrf
    @method('PUT')
    <div class="card mb-4">
    <div class="card-body">
        <div class="form-group">
            <label for="judul">Judul Artikel</label>
            <input type="text" class="form-control" id="judul" name="judul" value="{{ old('judul',$post->judul) }}" placeholder="Judul Artikel">
            @error('judul')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror

            <br><br>
            <label for="isi_artikel">Isi Artikel</label>
            <input type="text" class="form-control" id="isi_artikel" name="isi_artikel" value="{{ old('isi_artikel',$post->isi_artikel) }}" placeholder="Isi Artikel">
            @error('isi_artikel')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror

        </div>
        <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Update</button>
        </div>
        </form>
</div>
</div>
</div>
@endsection

resources/views/articles/index.blade.php
@extends('..layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
            <!-- Blog Post -->
            
            <div class="card">
            @forelse($article as $key => $post)
                <!-- <img src="http://placehold.it/750x300"> -->
                <div class="card-body">
                
                <h2 class="card-title">{{$post->judul}}</h2>
                <p class="card-text">{{substr($post->isi_artikel, 0, 250)}}</p>
                <a href="{{ route('articles.show',['article'=>$post->id]) }}" class="btn btn-primary">Read More &rarr;</a>
                
                </div>
                <div class="card-footer text-muted">
                Posted on {{$post->updated_at}} by
                <a href="#">{{ Auth::user()->name }}</a>
                <div class="d-flex">
                <!-- <a href="{{ route('articles.show',['article'=>$post->id]) }}" class="btn btn-info btn-sm">show</a>-->
                <a href="{{ route('articles.edit',['article'=>$post->id]) }}" class="btn btn-default btn-sm">edit</a>
                <form action="{{ route('articles.destroy',['article'=>$post->id]) }}" method="post">
                    @csrf
                    @method('DELETE')
                    <input type="submit" value="delete" class="btn btn-danger btn-sm">
                </form>
                </div>
                </div>
                @empty
                Tidak Ada Artikel
                @endforelse    
            </div>
                   
            

            <!-- Pagination -->
            <ul class="pagination justify-content-center">
                <li class="page-item">
                <a class="page-link" href="#">&larr; Older</a>
                </li>
                <li class="page-item disabled">
                <a class="page-link" href="#">Newer &rarr;</a>
                </li>
            </ul>

            </div>
            
        </div>
        </div>
    </div>
</div>
@endsection

resources/views/articles/show.blade.php
@extends('..layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
        <div class="card mb-4">
        <div class="card-body">
        <div class="form-group">
        <h2 class="card-title">{{$post->judul}}</h2>
        <p class="card-text">{{$post->isi_artikel}}</p>

        <form role="form" action="{{ route('comments.store',['comment'=>$post->id]) }}" method="post">
        @csrf
        <h5 class="card-title">Post Comment:</h5>
        <textarea class="form-control" id="isi_komentar" name="isi_komentar" value="{{ old('isi_komentar','') }}"  style="height:200px" placeholder="Isi Komentar"></textarea>
        <button type="submit" class="btn btn-primary">Submit</button>
        </form>

        <br><p class="card-text">Komentar:</p> -->
        
        <p class="card-text">{{$post->isi_komentar}}</p>
        

        </div>
        </div>  
        </div>
        </div>
        </div>
    </div>
@endsection

resources/views/createprofile.blade.php
@extends('layouts.app')
@section('content')

<div class="container">
<div class="row justify-content-center">
<div class="col-md-8">
<div class="card">
<form role="form" action="/profile" method="post">
    @csrf
    @method('PUT')
    <div class="card mb-4">
    <div class="card-body">
        <div class="form-group">
            <label for="nama_lengkap">Nama Lengkap</label>
            <input type="text" class="form-control" id="nama_lengkap" name="nama_lengkap" value="{{ old('nama_lengkap',$post->nama_lengkap) }}" placeholder="Nama Lengkap">

            <br><br>
            <label for="photo">Photo</label>
            <input type="text" class="form-control" id="photo" name="photo" value="{{ old('photo',$post->photo) }}" placeholder="Photo">
           
            <br><br>
            <label for="jumlah_artikel">Jumlah Artikel</label>
            <input type="text" class="form-control" id="jumlah_artikel" name="jumlah_artikel" value="{{ old('jumlah_artikel',$post->jumlah_artikel) }}" placeholder="Jumlah Artikel">
           
            <br><br>
            <label for="jumlah_following">Jumlah Following</label>
            <input type="text" class="form-control" id="jumlah_following" name="jumlah_following" value="{{ old('jumlah_following',$post->jumlah_following) }}" placeholder="Jumlah Following">
        
            <br><br>
            <label for="jumlah_follower">Jumlah Follower</label>
            <input type="text" class="form-control" id="jumlah_follower" name="jumlah_follower" value="{{ old('jumlah_follower',$post->jumlah_follower) }}" placeholder="Jumlah Follower">

        </div>
        <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Update</button>
        </div>
        </form>   
            </div>
            </div>
            </div>
            </div>
        </div>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
            <div class="card">
            @forelse($article as $key => $post)
                <!-- <img src="http://placehold.it/750x300"> -->
                <div class="card-body">
                
                <h2 class="card-title">{{$post->judul}}</h2>
                <p class="card-text">{{substr($post->isi_artikel, 0, 250)}}</p>
                <a href="{{ route('articles.show',['article'=>$post->id]) }}" class="btn btn-primary">Read More &rarr;</a>
                
                </div>
                <div class="card-footer text-muted">
                Posted on {{$post->updated_at}} by
                <a href="#">{{ Auth::user()->name }}</a>
                <div class="d-flex">
                <!-- <a href="{{ route('articles.show',['article'=>$post->id]) }}" class="btn btn-info btn-sm">show</a> -->
                <a href="{{ route('articles.edit',['article'=>$post->id]) }}" class="btn btn-default btn-sm">edit</a>
                <form action="{{ route('articles.destroy',['article'=>$post->id]) }}" method="post">
                    @csrf
                    @method('DELETE')
                    <input type="submit" value="delete" class="btn btn-danger btn-sm">
                </form>
                </div>
                </div>
                @empty
                Tidak Ada Artikel
                @endforelse    
            </div>
            
            

            <!-- Pagination -->
            <ul class="pagination justify-content-center">
                <li class="page-item">
                <a class="page-link" href="#">&larr; Older</a>
                </li>
                <li class="page-item disabled">
                <a class="page-link" href="#">Newer &rarr;</a>
                </li>
            </ul>

            </div>
            
        </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>..::: B L O G :::..</title>
    <!-- {{ config('app.name', 'Laravel') }} -->

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    ..::: B L O G :::..
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                  
                                <a class="dropdown-item" href="/profile/{{ Auth::user()->id }}">
                                        {{ __('My Profile') }}
                                    </a>
                                    <a class="dropdown-item" href="/articles/show/{{ Auth::user()->id }}">
                                        {{ __('My Articles') }}
                                    </a>
                                
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                    document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                   
                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/profile.blade.php
@extends('layouts.app')
@section('content')

<div class="container">
<div class="row justify-content-center">
<div class="col-md-8">
<div class="card">

    @csrf
    @method('POST')
    <div class="card mb-4">
    <div class="card-body">
        <div class="form-group">
            <label for="nama_lengkap">Nama Lengkap</label>
            <input type="text" class="form-control" id="nama_lengkap" name="nama_lengkap" value="{{ old('nama_lengkap',$post->nama_lengkap) }}" placeholder="Nama Lengkap">

            <br><br>
            <label for="photo">Photo</label>
            <input type="text" class="form-control" id="photo" name="photo" value="{{ old('photo',$post->photo) }}" placeholder="Photo">
           
            <br><br>
            <label for="jumlah_artikel">Jumlah Artikel</label>
            <input type="text" class="form-control" id="jumlah_artikel" name="jumlah_artikel" value="{{ old('jumlah_artikel',$post->jumlah_artikel) }}" placeholder="Jumlah Artikel">
           
            <br><br>
            <label for="jumlah_following">Jumlah Following</label>
            <input type="text" class="form-control" id="jumlah_following" name="jumlah_following" value="{{ old('jumlah_following',$post->jumlah_following) }}" placeholder="Jumlah Following">
        
            <br><br>
            <label for="jumlah_follower">Jumlah Follower</label>
            <input type="text" class="form-control" id="jumlah_follower" name="jumlah_follower" value="{{ old('jumlah_follower',$post->jumlah_follower) }}" placeholder="Jumlah Follower">

        </div>
        <!-- /.card-body -->

        <div class="card-footer">
        <!-- <form role="form" action="/articles/create" method="post"> -->
            <a class="btn btn-primary" href="/articles/create">Buat Artikel Baru</a>
        <!-- </form> -->
        </div>   
            </div>
            </div>
            </div>
            </div>
        </div>

@endsection